version: "3.9"

services:
  #1 service - web
  web:
    #Specifying name of container
    container_name: simple-webapp-2
    #Will use current context dockerfile for build
    build:
      context: .
      dockerfile: Dockerfile
    #Mount project directory & node_modules directory
    volumes:
      - ./:/app
      - /app/node_modules
    #Will expose and map port 3000:3000
    ports:
      - "3000:3000"
  redis:
    image: "redis:alpine"